// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"adecd2ce582e4f78038bde6ba1c618bf6737b14a3df57eb2ea5c7f3a51c08373ad6868c07960af47a0852ba629150cebcc7fa41ba1ce82ab5d719523aa01f5bd","First VB Variable":"11","First VB Switch":"11","Is Server":"true"}}
];
